## einsum

In [23]:
import torch

x = torch.rand((2,3))
print(x)
#permutation
torch.einsum("ij->ji",x)
print(x)

#summation:
y = torch.einsum("ij->",x)
print(y)

#column sum
a = torch.einsum("ij->j",x)
print(a)

#row sum
b = torch.einsum("ij->i", x)
print(b)

#matrix vector multipication:
v = torch.rand((1,3))   #here will no require to transpose
c = torch.einsum("ij, kj -> ik", x, v)
print(c)
#matrix matrix multipication:
print(torch.einsum("ij,kj->ik",x,x))

#dot product of first row
torch.einsum("i,i->",x[0],x[0])

#dot product of matrix
torch.einsum("ij,ij->",x,x)

#hadamard
torch.einsum("ij,ij->ij",x,x)

# outer producr
a = torch.rand((3))
b = torch.rand((5))
# print(torch.einsum("i,j->ij",a,b))



#batch matrix mul
a = torch.rand((3,2,5))
b = torch.rand((3,5,3))
torch.einsum("ijk, ikl -> ijl", a,b)

#diagonal 
x = torch.rand((3,3))
torch.einsum("ii->i",x)

#matrix trace
torch.einsum("ii->",x)

tensor([[0.1821, 0.3091, 0.4482],
        [0.1964, 0.5262, 0.4205]])
tensor([[0.1821, 0.3091, 0.4482],
        [0.1964, 0.5262, 0.4205]])
tensor(2.0824)
tensor([0.3785, 0.8353, 0.8687])
tensor([0.9394, 1.1430])
tensor([[0.1335],
        [0.1541]])
tensor([[0.3296, 0.3869],
        [0.3869, 0.4922]])


tensor(0.8910)